config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/dashboard', to: 'pages#dashboard'
  resources :doubles do
    resources :bookings, only: [ :new, :create ]
  end
  resources :bookings, only: [ :show, :destroy ] do
    resources :reviews, only: [ :new, :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :double
  has_many :reviews
  validates :start_date, :end_date, presence: true
end

app/models/double.rb
CATEGORIES = ['Tv', 'Cinema', 'Comedy', 'Music', 'Politics', 'Sport', 'Animals', 'Others']

class Double < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many :reviews, through: :bookings
  validates :price, :name, :address, presence: true
  validates :category, inclusion: { in: CATEGORIES }

  has_one_attached :photo

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch::Model
  pg_search_scope :search_by_name_and_description_and_category,
    against: {
      name: 'A',
      description: 'B',
      category: 'C'
    },
    using: {
      tsearch: { prefix: true }
    }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  validates :rating, inclusion: { in: (1..5),
    message: "%{value} is not a valid rating" }
  validates :comment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :doubles
  has_many :bookings
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, uniqueness: true, presence: true
  after_create :send_welcome_email

  private

  def send_welcome_email
    UserMailer.with(user: self).welcome.deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit
  before_action :disable_nav, only: [:home]


  after_action :verify_authorized, except: :home, unless: :skip_pundit?
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?
  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def disable_nav
    @disable_nav = true
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new
    authorize @booking
    @double = Double.find(params[:double_id])
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    authorize @booking
    @double = Double.find(params[:double_id])
    @booking.double = @double
    @booking.total_price = (params[:booking][:end_date].to_date - params[:booking][:start_date].to_date).to_i * @double.price
    if @booking.save
      redirect_to dashboard_path
    else
      render "doubles/show"
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to root_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :user_id, :total_price)
  end
end

app/controllers/doubles_controller.rb
class DoublesController < ApplicationController
  before_action :set_double, only: [:show, :edit, :update, :destroy]

  def index
    if params[:query].present?
      sql_query = "name ILIKE :query OR description ILIKE :query"
      @doubles = policy_scope(Double.includes(:photo_attachment)).where(sql_query, query: "%#{params[:query]}%")
    elsif (params[:query] == "" || params[:query].nil?) && params[:category].present?
      sql_query = "category ILIKE :category"
      @doubles = policy_scope(Double.includes(:photo_attachment)).where(sql_query, category: "%#{params[:category]}%")
    else
      @doubles = policy_scope(Double.includes(:photo_attachment))
    end
    @markers = @doubles.geocoded.map do |double|
      {
        lat: double.latitude,
        lng: double.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { double: double })
        # image_url: helpers.asset_url('REPLACE_THIS_WITH_YOUR_IMAGE_IN_ASSETS')
      }
    end
  end

  def show
    authorize @double
    @booking = Booking.new
    @bookings = Booking.where(double_id: @double.id)
    @bookings_dates = @bookings.map do |booking|
      {
        from: booking.start_date,
        to:   booking.end_date
      }
    end
  end

  def new
    @double = Double.new
    authorize @double
  end

  def create
    @double = Double.new(double_params)
    authorize @double
    @double.user = current_user
    if @double.save
      mail = DoubleMailer.with(double: @double).create_confirmation
      mail.deliver_now
      redirect_to double_path(@double)
    else
      render :new
    end
  end

  def edit
    authorize @double
  end

  def update
    authorize @double
    @double.user = current_user
    @double.update(double_params)
    redirect_to double_path
  end

  def destroy
    @double.destroy
    authorize @double
    redirect_to doubles_path
  end

  private
  def set_double
    @double = Double.find(params[:id])
  end
  def double_params
    params.require(:double).permit(:price, :name, :address, :category, :description, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end

  def dashboard
    @doubles = current_user.doubles.includes(:photo_attachment)
    @bookings = current_user.bookings
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
  end

  def new
  end

  def create
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/destroy.html.erb
<h1>Bookings#destroy</h1>
<p>Find me in app/views/bookings/destroy.html.erb</p>

app/views/bookings/new.html.erb
<div class="newbooking my-5">
  <div class="container">
    <div class="double-name">
      <h1>Book <%= @double.name %></h1>
    </div>
    <div class=""></div>
    <hr>
    <%= simple_form_for [@double, @booking] do |f| %>
      <%= f.input :start_date %>
      <%= f.input :end_date %>
      <%= f.submit class: "btn btn-success"%>
    <% end %>
  </div>
</div>

app/views/doubles/_info_window.html.erb
<div id="popup_content">
  <%= link_to double_path(double) do %>
    <h5>
      <%= double.name %>
      <% case %>
        <% when double.category == "Music" %>
          <i class="fas fa-music"></i>
        <% when double.category == "Cinema" %>
          <i class="fas fa-film"></i>
        <% when double.category == "Politics" %>
          <i class="fas fa-handshake"></i>
        <% when double.category == "Comedy" %>
          <i class="fas fa-theater-masks"></i>
        <% when double.category == "Tv" %>
          <i class="fas fa-tv"></i>
        <% when double.category == "Sport" %>
          <i class="fas fa-futbol"></i>
        <% end %>
    </h5>
    <p><i class="fas fa-map-marker-alt"></i> <%= double.address %></p>
  <% end %>
</div>

app/views/doubles/edit.html.erb
<div class="container my-5">
  <h1>Update <%= @double.name %></h1>
  <%= render 'shared/doubles_form', double: @double %>
</div>

app/views/doubles/index.html.erb
<div class="main-container">
  <div class="grid-index">
    <% @doubles.each do |double| %>
    <% if double.photo.attached? %>
      <%= link_to double_path(double) do %>
        <div class="card shadow mb-5 bg-white" style="width: 18rem;">
          <%= cl_image_tag(double.photo.key, gravity: "face", crop: "fill") %>
            <div class="card-body">
              <h5 class="card-title">
                <div id="card-name-category">
                  <%= double.name %>
                  <% case %>
                    <% when double.category == "Music" %>
                      <i class="fas fa-music"></i>
                    <% when double.category == "Cinema" %>
                      <i class="fas fa-film"></i>
                    <% when double.category == "Politics" %>
                      <i class="fas fa-handshake"></i>
                    <% when double.category == "Comedy" %>
                      <i class="fas fa-theater-masks"></i>
                    <% when double.category == "Tv" %>
                      <i class="fas fa-tv"></i>
                    <% when double.category == "Sport" %>
                      <i class="fas fa-futbol"></i>
                  <% end %>
                </div>
              </h5>
              <h6 class="card-subtitle py-1"><i class="fas fa-tag"></i> <%= double.price.to_i %>€ /day</h6>
              <p class="card-text py-1"><i class="fas fa-map-marker-alt"></i> <%= double.address %></p>
            </div>
        </div>
      <% end %>
    <% else %>
      <%= link_to double_path(double) do %>
        <div class="card shadow mb-5 bg-white" style="width: 18rem;">
        <%= image_tag 'no-photo-placeholder.png' %>
          <div class="card-body">
            <h5 class="card-title">
              <div id="card-name-category">
                <%= double.name %>
                <% case %>
                  <% when double.category == "Music" %>
                    <i class="fas fa-music"></i>
                  <% when double.category == "Cinema" %>
                    <i class="fas fa-film"></i>
                  <% when double.category == "Politics" %>
                    <i class="fas fa-handshake"></i>
                  <% when double.category == "Comedy" %>
                    <i class="fas fa-theater-masks"></i>
                  <% when double.category == "Tv" %>
                    <i class="fas fa-tv"></i>
                  <% when double.category == "Sport" %>
                    <i class="fas fa-futbol"></i>
                <% end %>
              </div>
            </h5>
            <h6 class="card-subtitle py-1"><i class="fas fa-tag"></i> <%= double.price.to_i %>€</h6>
            <p class="card-text py-1"><i class="fas fa-map-marker-alt"></i> <%= double.address %></p>
          </div>
        </div>
      <% end %>
    <% end %>
    <% end %>
  </div>
  <div class="map-container">
    <div id="map"
      style="width: 100%; height: 600px;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>

app/views/doubles/new.html.erb
<div class="container">
  <h1>Add a new Doppleganger!</h1>
  <%= render 'shared/doubles_form', double: @double %>
</div>

app/views/doubles/show.html.erb
<div class="container">
  <% if @double.photo.attached? %>
      <div class="double-image"> <%= cl_image_tag(@double.photo.key, gravity: "face", crop: "fill", height: 358, width: 700) %></div>
  <% else %>
      <div class="double-image"> <%= image_tag 'no-photo-placeholder.png' %></div>
  <% end %>
    <div class="grid-show my-5">
      <div class="left-content">
          <div class="text">
            <div class="title-and-buttons">
            <h1><%= @double.name %></h1>
              <div class="buttons">
                <% if policy(@double).edit? %>
                  <%= link_to edit_double_path do %>
                    <%= icon('far', 'edit', class: 'px-2') %>
                  <% end %>
                  <%= link_to double_path(@double), method: :delete, data: { confirm:"Are you sure?" } do %>
                    <%= icon('far', 'trash-alt', class: 'px-2') %>
                  <% end %>
                <% end %>
              </div>
            </div>
            <h3 id="price" data-price="price"> Daily price: <%= @double.price.to_i %> €</h3>
            <h5><%= @double.address %></h5>
            <p><%= @double.description %></p>
          </div>
        </div>
      <div id="booking-form-div"
        data-bookings="<%= @bookings_dates.to_json %>">
          <%= simple_form_for [@double, @booking] do |f| %>
            <%= f.input :start_date, label: "Select your date(s):", as: :string, required: false, input_html: { id: "range_start", class: "d-none"} %>
            <%= f.input :end_date, label: false, as: :string, required: false, input_html: { id: "range_end", class: "d-none" } %>
            <%= f.button :submit, "Book", class: "btn-special" %>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Doppel</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' unless @disable_nav  %>
    <%= render 'shared/flashes' %>
    <div class="content-wrapper">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/layouts/footer.html.erb
<div class="footer">
  <div class="footer-logo">
    <%= image_tag "doppl_logo.png", alt: "doppel logo" %>
  </div>
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    This website was made with <i class="fas fa-heart"></i> by the Bolero team at Le Wagon.
  </div>
</div>

app/views/pages/dashboard.html.erb
<div class="container">
  <div class="welcome-heading d-flex justify-content-between align-items-start">
    <div class="welcome-text my-5">
      <h1>Hello <%= current_user.username %></h1>
      <h4>Nice to see you again!</h4>
    </div>
    <div class="welcome-tabs">
      <ul class="list-inline tabs-underlined">
        <li>
          <a href="#" id="booking" class="tab-underlined active">Bookings</a>
        </li>
        <li>
          <a href="#" id="doppel" class="tab-underlined">DoppelsGangers</a>
        </li>
      </ul>
    </div>
  </div>

  <div class="booking my-5">
    <% if current_user.bookings.size > 0 %>
      <% @bookings.each do |booking| %>
        <div class="dash-card">
          <div class="dash-card-infos">
            <h3><%= booking.double.name %></h3>
            <p><strong>From</strong> <span class="text-muted"><%= booking.start_date.to_date %></span></p>
            <p><strong>To</strong> <span class="text-muted"><%= booking.end_date.to_date %></span></p>
            <p>
              <%= truncate booking.double.description, length: 200 %>
              <%= link_to 'more', double_path(booking.double) %>
            </p>
            <p><strong>Total price</strong>: <%= booking.total_price.to_i %>€</p>
          </div>
          <div class="dash-card-img">
            <% if booking.double.photo.attached? %>
              <%= cl_image_tag(booking.double.photo.key, gravity: "face", crop: "fill") %>
            <% else %>
              <%= imate_tag 'no-photo-placeholder.png' %>
            <% end %>
          </div>
        </div>
      <% end %>
    <% else %>
      <div class="booking-card">
        <h4>You don't have any booking yet!</h4>
      </div>
    <% end %>
  </div>

  <div class="doppel hidden my-5">
    <% if current_user.doubles.size > 0 %>
      <% @doubles.each do |double| %>
          <div class="dash-card">
            <div class="dash-card-infos">
              <h3><%= double.name %></h3>
              <p>
                <%= truncate double.description, length: 200 %>
                <%= link_to 'more', double_path(double) %>
              </p>
              <p><%= double.price.to_i %>€ /day</p>
              <p>
                <%= link_to edit_double_path(double) do %>
                  <%= icon('far', 'edit', class: 'px-2') %>
                <% end %>
                <%= link_to double_path(double), method: :delete, data: { confirm: "Are you sure?" } do %>
                  <%= icon('far', 'trash-alt', class: 'px-2') %>
                <% end %>
              </p>
            </div>
            <div class="dash-card-img">
            <% if double.photo.attached? %>
              <%= cl_image_tag(double.photo.key, gravity: "face", crop: "fill") %>
            <% else %>
              <%= image_tag 'no-photo-placeholder.png' %>
            <% end %>
            </div>
          </div>
        <% end %>
    <% else %>
      <div class="double-card">
        <h4>You don't have any Doppelgangers yet!</h4>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
  <%= render 'shared/navbar_home' %>

  <div class="hero">
    <div class="text-header d-flex justify-content-center align-items-center">
      <%= image_tag "doppl_logo.png", alt: "doppel logo" %>
      <h1>The best place to rent doubles</h1>
    </div>
    <div class="down-arrow d-flex justify-content-center align-items-end">
      <a href="#scroll"><%= icon('fas','chevron-down') %></a>
    </div>
  </div>

  <div class="container my-5" id="scroll">
  
    <div class="wrapper mb-5">
      <%= form_tag doubles_path, method: :get, :class => "searchbar-container" do %>
        <div class="search-field">
          <%= text_field_tag :query,
              params[:query],
              class: "form-control",
              placeholder: "Type a celebrity's name"
          %>
        </div>
        <div class="search-field">
          <%= select_tag "category",
            options_for_select([ 'Choose category', 'Tv', 'Cinema', 'Comedy', 'Music', 'Politics', 'Sport', 'Animals', 'Others' ], ''),
            class: "form-control"
          %>
        </div>
        <%= submit_tag "Search", class: "btn-special btnsub" %>
      <% end %>
    </div>

    <div id="categories">
      <div class="row">
        <div class="col-12 col-md-6 col-lg-4">
          <%= link_to doubles_path(category: "Tv") do %>
            <div class="cards shadow mb-5 bg-white rounded">
              <div class="card tv justify-content-center align-items-center">
                <h2>TV</h2>
              </div>
            </div>
          <% end %>
        </div>
        <div class="col-12 col-md-6 col-lg-4">
          <%= link_to doubles_path(category: "Cinema") do %>
            <div class="cards shadow mb-5 bg-white rounded">
              <div class="card cine justify-content-center align-items-center">
                <h2>CINEMA</h2>
              </div>
            </div>
          <% end %>
        </div>
        <div class="col-12 col-md-6 col-lg-4">
          <%= link_to doubles_path(category: "Comedy") do %>
            <div class="cards shadow mb-5 bg-white rounded">
              <div class="card comedy justify-content-center align-items-center">
                <h2>COMEDY</h2>
              </div>
            </div>
          <% end %>
        </div>
        <div class="col-12 col-md-6 col-lg-4">
          <%= link_to doubles_path(category: "Music") do %>
            <div class="cards shadow mb-5 bg-white rounded">
              <div class="card music justify-content-center align-items-center">
                <h2>MUSIC</h2>
              </div>
            </div>
          <% end %>
        </div>
        <div class="col-12 col-md-6 col-lg-4">
          <%= link_to doubles_path(category: "Politics") do %>
            <div class="cards shadow mb-5 bg-white rounded">
              <div class="card politic justify-content-center align-items-center">
                <h2>POLITICS</h2>
              </div>
            </div>
          <% end %>
        </div>
        <div class="col-12 col-md-6 col-lg-4">
          <%= link_to doubles_path(category: "Sport") do %>
            <div class="cards shadow mb-5 bg-white rounded">
              <div class="card sport justify-content-center align-items-center">
                <h2>SPORT</h2>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/index.html.erb
<h1>Reviews#index</h1>
<p>Find me in app/views/reviews/index.html.erb</p>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>

app/views/shared/_doubles_form.html.erb
<div class="container my-5">
  <%= simple_form_for double do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :price, :label => "Price per day" %>
    <%= f.input :category, collection: CATEGORIES %>
    <%= f.input :description %>
    <%= f.input :photo, as: :file %>
    <%= f.submit class: "btn-special btnsub" %>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <%= image_tag "doppl_logo.png", alt: "doppel logo", class: "footer-logo" %>
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    This website was made with <i class="fas fa-heart"></i> by the Bolero team at Le Wagon.
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar fixed-top navbar-expand-sm navbar-light navbar-lewagon-2">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "doppl_logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>

        <li class="nav-item active">
          <%= link_to "Doppels", doubles_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <p class="nav-link noHover"><%= current_user.username %></p>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://avatars3.githubusercontent.com/u/71142027?v=4", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
            <%= link_to "Add a doppelganger", new_double_path, class: "dropdown-item" %>
            <%= link_to "Edit your account", edit_user_registration_path , class: "dropdown-item"%>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://themindsetproject.com.au/wp-content/uploads/2017/08/avatar-icon-300x300.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Sign up", new_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Log in", new_user_session_path, class: "dropdown-item" %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_navbar_home.html.erb
<div class="navbar fixed-top navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "doppl_logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Doppels", doubles_path, class: "nav-link text-white" %>
        </li>
        <li class="nav-item">
          <p class="nav-link text-white noHover"><%= current_user.username %></p>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://avatars3.githubusercontent.com/u/71142027?v=4", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
            <%= link_to "Add a doppelganger", new_double_path, class: "dropdown-item" %>
            <%= link_to "Edit your account", edit_user_registration_path , class: "dropdown-item"%>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://themindsetproject.com.au/wp-content/uploads/2017/08/avatar-icon-300x300.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Sign up", new_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Log in", new_user_session_path, class: "dropdown-item" %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>